proj_example/basic/movies/urls.py
from django.conf.urls.defaults import *
from basic.movies.models import *


genre_list = {
    'queryset': Genre.objects.all(),
}
movie_list = {
    'queryset': Movie.objects.all(),
}
studio_list = {
    'queryset': Studio.objects.all(),
}


urlpatterns = patterns('django.views.generic.list_detail',
    url(r'^genres/(?P<slug>[-\w]+)/$',
        view='object_detail',
        kwargs=genre_list,
        name='movie_genre_detail',
    ),
    url (r'^genres/$',
        view='object_list',
        kwargs=genre_list,
        name='movie_genre_list',
    ),
    url(r'^studios/(?P<slug>[-\w]+)/$',
        view='object_detail',
        kwargs=studio_list,
        name='movie_studio_detail',
    ),
    url (r'^studios/$',
        view='object_list',
        kwargs=studio_list,
        name='movie_studio_list',
    ),
    url(r'^(?P<slug>[-\w]+)/$',
        view='object_detail',
        kwargs=movie_list,
        name='movie_detail',
    ),
    url (r'^$',
        view='object_list',
        kwargs=movie_list,
        name='movie_list',
    ),
)

proj_example/urls.py
# -*- encoding: utf-8 -*-

from django.conf.urls.defaults import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'proj_example.views.home', name='home'),
    url(r'^music/', include('proj_example.basic.music.urls')),
    url(r'^people/', include('proj_example.basic.people.urls')),
    url(r'^movies/', include('proj_example.basic.movies.urls')),
    url(r'^books/', include('proj_example.basic.books.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

"""
Se o modo debug está ligado, significa que está em ambiente de desenvolvimento,
entao o django passa a servir arquivos estáticos.
"""
if settings.DEBUG == True:
    urlpatterns += patterns('',
        (r'^media/(.*)','django.views.static.serve',{'document_root':settings.MEDIA_ROOT}),
        (r'^static/(.*)','django.views.static.serve',{'document_root':settings.STATIC_ROOT}),
    )

proj_example/basic/movies/models.py
from django.db import models
from django.db.models import permalink
from django.conf import settings
from basic.people.models import Person


class Genre(models.Model):
    """Genre model"""
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)

    class Meta:
        db_table = 'movie_genres'
        ordering = ('title',)

    def __unicode__(self):
        return '%s' % self.title

    @permalink
    def get_absolute_url(self):
        return ('movie_genre_detail', None, { 'slug': self.slug })


class Studio(models.Model):
    """Studio model"""
    title = models.CharField(max_length=100)
    prefix = models.CharField(max_length=20, blank=True)
    slug = models.SlugField(unique=True)
    website = models.URLField(blank=True, verify_exists=False)

    class Meta:
        db_table = 'movie_studios'
        ordering = ('title',)

    def __unicode__(self):
        return '%s' % self.full_title

    @property
    def full_title(self):
        return '%s %s' % (self.prefix, self.title)

    @permalink
    def get_absolute_url(self):
        return ('movie_studio_detail', None, { 'slug': self.slug })


class Movie(models.Model):
    """Movie model"""
    title = models.CharField(max_length=255)
    prefix = models.CharField(max_length=20, blank=True)
    subtitle = models.CharField(blank=True, max_length=255)
    slug = models.SlugField(unique=True)
    directors = models.ManyToManyField(Person, limit_choices_to={'person_types__slug__exact': 'director'}, blank=True)
    studio = models.ForeignKey(Studio, blank=True, null=True)
    released = models.DateField(blank=True, null=True)
    asin = models.CharField(blank=True, max_length=100)
    cover = models.FileField(upload_to='films', blank=True)
    review = models.TextField(blank=True)
    genre = models.ManyToManyField(Genre, blank=True)

    class Meta:
        db_table = 'movies'
        ordering = ('title',)

    def __unicode__(self):
        return '%s' % self.full_title

    @property
    def full_title(self):
        return '%s %s' % (self.prefix, self.title)

    @permalink
    def get_absolute_url(self):
        return ('movie_detail', None, { 'slug': self.slug })

    @property
    def amazon_url(self):
        try:
            return 'http://www.amazon.com/dp/%s/?%s' % (self.asin, settings.AMAZON_AFFILIATE_EXTENTION)
        except:
            return 'http://www.amazon.com/dp/%s/' % self.asin

    @property
    def cover_url(self):
        return '%s%s' % (settings.MEDIA_URL, self.cover)

proj_example/basic/movies/templates/movies/_nav.html
<div id="section_nav">
  <ul>
    <li class="music"><a href="{% url music_index %}">Music</a></li>
    <li class="movies"><a href="{% url movie_list %}">Movies</a>
      <ul>
        <li class="genres"><a href="{% url movie_genre_list %}">Genres</a></li>
        <li class="studios"><a href="{% url movie_studio_list %}">Studios</a></li>
      </ul>
    </li>
    <li class="books"><a href="{% url book_list %}">Books</a></li>
  </ul>
</div>

proj_example/basic/movies/templates/movies/base_movies.html
{% extends "base.html" %}


{% block body_class %}movies{% endblock %}

proj_example/basic/movies/templates/movies/genre_detail.html
{% extends "movies/base_movies.html" %}


{% block title %}{{ object.title }}{% endblock %}
{% block body_class %}{{ block.super }} movie_genres{% endblock %}


{% block content_title %}
  <h2>Movie Genres</h2>
  {% include "movies/_nav.html" %}
{% endblock %}


{% block content %}
  <h3>{{ object.title }}</h4>
  <ul class="link_list">
    {% for movie in object.movie_set.all %}
    <li><a href="{{ movie.get_absolute_url }}">{{ movie.full_title }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

proj_example/basic/movies/templates/movies/genre_list.html
{% extends "movies/base_movies.html" %}


{% block title %}Movie Genres{% endblock %}
{% block body_class %}{{ block.super }} movie_genres{% endblock %}


{% block content_title %}
  <h2>Movie Genres</h2>
  {% include "movies/_nav.html" %}
{% endblock %}


{% block content %}
  <ul class="link_list">
  {% for genre in object_list %}
    <li><a href="{{ genre.get_absolute_url }}">{{ genre.title }}</a></li>
  {% endfor %}
  </ul>
{% endblock %}

proj_example/basic/movies/templates/movies/movie_detail.html
{% extends "movies/base_movies.html" %}


{% block title %}{{ object.full_title }}{% endblock %}


{% block content_title %}
  <h2>Movies</h2>
  {% include "movies/_nav.html" %}
{% endblock %}


{% block content %}
  {% load markup %}
  <h3>{{ object.full_title }}
  {% if object.subtitle %}<em>{{ object.subtitle }}</em></h3>{% endif %}
  
  {% if object.cover %}
  <a class="cover" href="{{ object.amazon_url }}"><img src="{{ object.cover_url }}" alt="Movie cover"></a>
  {% else %}
  <div class="no_cover"></div>
  {% endif %}
  
  <ul class="info_list">
    <li>Directors: {% for director in object.directors.all %}<a href="{{ director.get_absolute_url }}">{{ director.full_name }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}</li>
    <li>Studio: <a href="{{ object.studio.get_absolute_url }}">{{ object.studio.full_title }}</a></li>
    <li>Released: {{ object.released|date:"d F Y" }}</li>
    <li>Genre: {% for genre in object.genre.all %}{{ genre.title }}{% if not forloop.last %}, {% endif %}{% endfor %}</li>
    <li>ASIN: {{ object.asin }} (<a href="{{ object.amazon_url }}">Amazon</a>)</li>
  </ul>
  
  {% if object.review %}
  <div class="review">
    <h4>Review</h4>
    {{ object.review|markdown:"safe" }}
  </div>
  {% endif %}
{% endblock %}

proj_example/basic/movies/templates/movies/movie_list.html
{% extends "movies/base_movies.html" %}


{% block title %}Movies{% endblock %}


{% block content_title %}
  <h2>Movies</h2>
  {% include "movies/_nav.html" %}
{% endblock %}


{% block content %}
  <ul class="link_list">
  {% for movie in object_list %}
    <li><a href="{{ movie.get_absolute_url }}">{{ movie.full_title }}</a></li>
  {% endfor %}
  </ul>
{% endblock %}

proj_example/basic/movies/templates/movies/studio_detail.html
{% extends "movies/base_movies.html" %}


{% block title %}{{ object.full_title }}{% endblock %}
{% block body_class %}{{ block.super }} movie_studios{% endblock %}


{% block content_title %}
  <h2>Movie Studios</h2>
  {% include "movies/_nav.html" %}
{% endblock %}


{% block content %}
  <h3>{{ object.full_title }}</h3>
  <ul class="link_list">
    {% for movie in object.movie_set.all %}
    <li><a href="{{ movie.get_absolute_url }}">{{ movie.full_title }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

proj_example/basic/movies/templates/movies/studio_list.html
{% extends "movies/base_movies.html" %}


{% block title %}Movie Studios{% endblock %}
{% block body_class %}{{ block.super }} movie_studios{% endblock %}


{% block content_title %}
  <h2>Movie Studios</h2>
  {% include "movies/_nav.html" %}
{% endblock %}


{% block content %}
  <ul class="link_list">
  {% for studio in object_list %}
    <li><a href="{{ studio.get_absolute_url }}">{{ studio.full_title }}</a></li>
  {% endfor %}
  </ul>
{% endblock %}